CREATE TABLE `Composers` (
  `composer_id` int NOT NULL AUTO_INCREMENT,
  `era` varchar(50) DEFAULT NULL,
  `nationality` varchar(20) DEFAULT NULL,
  `last_name` varchar(50) DEFAULT NULL,
  `first_name` varchar(50) DEFAULT NULL,
  `birth_date` date DEFAULT NULL,
  `death_date` date DEFAULT NULL,
  PRIMARY KEY (`composer_id`)
)


INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (1,'Contemporary','Indian','Rahman','A. R.','1967-01-06',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (2,'20th Century','American','Copland','Aaron','1900-11-14','1990-12-02');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (3,'20th Century','Austrian','Berg','Alban','1885-02-09','1935-12-24');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (4,'20th Century','English','Lloyd Webber','Andrew','1948-03-22',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (5,'20th Century','German, American','Previn','André','1929-04-06','2019-02-28');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (6,'Post-Romantic','Austrian','Bruckner','Anton','1824-09-04','1896-10-11');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (7,'Post-Romantic','Czech','Dvořák','Antonín','1841-09-08','1904-05-01');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (8,'Classical','Italian','Salieri','Antonio','1750-08-18','1825-05-07');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (9,'Baroque','Italian ','Vivaldi','Antonio','1678-03-04','1741-07-28');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (10,'20th Century','Austrian ','Schoenberg','Arnold','1874-09-13','1951-07-13');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (11,'20th Century','Estonian','Pärt','Arvo','1935-09-11',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (12,'20th Century','Argentine','Piazzolla','Astor','1921-03-11','1992-07-04');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (13,'Romantic','Czech','Smetana','Bedřich','1824-03-02','1884-05-12');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (14,'20th Century','English ','Britten','Benjamin','1913-11-22','1976-12-04');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (15,'20th Century','American ','Herrmann','Bernard','1911-06-29','1975-12-24');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (16,'21st Century','American ','Tyler','Brian','1972-05-08',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (17,'20th Century','American ','Bacharach','Burt','1928-05-12',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (18,'20th Century','Hungarian','Bartók','Béla','1881-03-25','1945-09-26');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (19,'Romantic','French ','Saint-Saëns','Camille','1835-10-09','1921-12-16');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (20,'Romantic','German','Von Weber','Carl Maria','1786-11-19','1826-06-05');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (21,'20th Century','American ','Ives','Charles','1874-10-20','1954-05-19');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (22,'Romantic','German','Schumann','Clara','1819-09-13','1896-05-20');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (23,'20th Century','French ','Debussy','Claude','1862-08-22','1918-03-25');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (24,'Baroque','Italian','Monteverdi','Claudio','1567-05-15','1643-11-29');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (25,'20th Century','American ','Porter','Cole','1891-06-09','1964-10-15');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (26,'Romantic','French','Franck','César','1822-12-10','1890-11-08');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (27,'20th Century','American','Brubeck','Dave','1920-12-06','2012-12-05');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (28,'20th Century','American','Diamond','David','1915-07-09','2005-06-13');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (29,'20th Century','English','Derbyshire','Delia','1937-05-05','2001-07-03');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (30,'20th Century','Russian','Shostakovich','Dmitri','1906-09-25','1975-08-09');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (31,'Baroque','Italian','Scarlatti','Domenico','1685-10-26','1757-07-23');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (32,'Post-Romantic','Norwegian','Grieg','Edvard','1843-06-15','1907-09-04');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (33,'20th Century','English ','Elgar','Edward','1857-06-02','1934-02-23');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (34,'20th Century','Italian','Morricone','Ennio','1928-11-10',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (35,'Contemporary','American','Whitacre','Eric','1970-01-02',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (36,'20th Century','French ','Satie','Erik','1866-05-17','1925-07-01');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (37,'Romantic','German ','Mendelssohn','Felix','1809-02-03','1847-11-04');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (38,'20th Century','American ','Zappa','Frank','1940-12-21','1993-12-04');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (39,'Romantic','Hungarian','Liszt','Franz','1811-10-22','1886-07-31');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (40,'Romantic','Austrian ','Schubert','Franz','1797-01-31','1828-11-19');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (41,'Romantic','Polish','Chopin','Frederic','1810-03-01','1849-10-17');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (42,'20th Century','French','Faure','Gabriel','1845-05-12','1924-11-04');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (43,'20th Century','Romanian','Enescu','George','1881-08-19','1955-05-04');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (44,'Baroque','British ','Handel','George Frideric','1685-02-23','1759-03-14');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (45,'20th Century','American ','Gershwin','George','1898-09-26','1937-07-11');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (46,'Romantic','French ','Bizet','Georges','1838-10-25','1875-06-03');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (47,'Post-Romantic','Italian ','Puccini','Giacomo','1858-12-22','1924-11-29');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (48,'20th Century','French','Bécaud','Gilbert','1927-10-24','2001-12-18');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (49,'Romantic','Italian ','Rossini','Gioachino','1792-02-29','1868-11-13');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (50,'Romantic','Italian','Verdi','Giuseppe','1813-10-10','1901-01-27');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (51,'20th Century','Bosnian ','Bregović','Goran','1950-03-22',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (52,'20th Century','English ','Holst','Gustav','1874-09-21','1934-05-25');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (53,'Post-Romantic','German ','Mahler','Gustav','1860-07-07','1911-05-18');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (54,'20th Century','German ','Zimmer','Hans','1957-09-12',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (55,'Contemporary','British ','Gregson-Williams','Harry','1961-12-13',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (56,'Romantic','French ','Berlioz','Hector','1803-12-11','1869-03-08');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (57,'20th Century','Brazilian','Villa-Lobos','Heitor','1887-03-05','1959-11-17');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (58,'Baroque','English ','Purcell','Henry','1659-09-10','1695-11-21');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (59,'20th Century','Canadian ','Shore','Howard','1946-10-18',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (60,'20th Century','Russian ','Stravinsky','Igor','1882-06-17','1971-04-06');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (61,'20th Century','American ','Berlin','Irving','1888-05-11','1989-09-22');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (62,'Post-Romantic','Spanish ','Albéniz','Isaac','1860-05-29','1909-05-18');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (63,'Baroque','French','Lully','Jean Baptiste','1632-11-28','1687-03-22');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (64,'Baroque','Genevan','Rousseau','Jean Jacques','1712-06-28','1778-07-02');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (65,'20th Century','Finnish','Sibelius','Jean','1865-12-08','1957-09-20');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (66,'Baroque','French ','Rameau','Jean-Philippe','1683-09-25','1764-09-12');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (67,'20th Century','American ','Goldsmith','Jerry','1929-02-10','2004-07-21');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (68,'20th Century','American ','Steinman','Jim','1947-11-01',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (69,'20th Century','Spanish','Rodrigo','Joaquin','1901-11-22','1999-07-06');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (70,'Contemporary','Japanese','Hisaishi','Joe','1950-12-06',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (71,'Baroque','German','Pachelbel','Johann','1653-09-01','1706-03-09');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (72,'Baroque','German ','Bach','Johann Sebastian','1685-03-31','1750-07-28');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (73,'Romantic','German ','Brahms','Johannes','1833-05-07','1897-04-03');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (74,'20th Century','English ','Barry','John','1933-11-03','2011-01-30');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (75,'20th Century','American ','Cage','John','1912-09-05','1992-08-12');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (76,'Renaissance','English ','Dowland','John','1563-09-15','1626-02-20');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (77,'20th Century','American ','Sousa','John Philip','1854-11-06','1932-03-06');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (78,'Contemporary','English','Powell','John','1963-09-18',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (79,'20th Century','English','Rutter','John','1945-09-24',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (80,'20th Century','English','Tavener','John','1944-01-28','2013-11-12');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (81,'20th Century','American ','Williams','John','1932-02-08',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (82,'Contemporary','American','Zorn','John','1953-09-02',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (83,'Classical','Austrian','Haydn','Franz Joseph','1732-03-31','1809-05-31');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (84,'Romantic','Mexican','Rosas','Juventino','1868-01-25','1894-07-09');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (85,'20th Century','Welsh','Jenkins','Karl','1944-02-17',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (86,'20th Century','German ','Stockhausen','Karlheinz','1928-08-22','2007-12-05');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (87,'Contemporary','German ','Badelt','Klaus','1967-06-12',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (88,'Contemporary','Japanese ','Kondo','Koji','1961-08-13',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (89,'20th Century','Polish ','Penderecki','Krzysztof','1933-11-23',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (90,'20th Century','German ','Weill','Kurt','1900-03-02','1950-04-03');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (91,'20th Century','American ','Young','La Monte','1935-10-14',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (92,'20th Century','American ','Bernstein','Leonard','1918-08-25','1990-10-14');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (93,'20th Century','Italian','Einaudi','Ludovico','1955-11-23',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (94,'Classical','German ','Van Beethoven','Ludwig','1770-12-17','1827-03-26');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (95,'20th Century','Spanish','De Falla','Manuel','1876-11-23','1946-11-14');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (96,'Contemporary','American ','Hamlisch','Marvin','1944-06-02','2012-08-06');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (97,'20th Century','French','Ravel','Maurice','1875-03-07','1937-12-28');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (98,'Contemporary','American ','Giacchino','Michael','1967-10-10',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (99,'20th Century','American ','Kamen','Michael','1948-04-15','2003-11-18');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (100,'20th Century','English ','Nyman','Michael','1944-03-23',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (101,'20th Century','French ','Legrand','Michel','1932-02-24',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (102,'Contemporary','English ','Oldfield','Mike','1953-05-15',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (103,'Romantic','Italian ','Paganini','Niccolò','1782-10-27','1840-05-27');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (104,'20th Century','Italian ','Rota','Nino','1911-12-03','1979-04-10');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (105,'Contemporary','Japanese ','Uematsu','Nobuo','1959-03-21',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (106,'20th Century','French ','Messiaen','Olivier','1908-12-10','1992-04-27');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (107,'20th Century','American ','Glass','Philip','1937-01-31',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (108,'20th Century','French ','Boulez','Pierre','1925-03-26',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (109,'Romantic','Russian','Tchaikovsky','Pyotr Ilyich','1840-05-07','1893-11-06');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (110,'20th Century','English ','Vaughan Williams','Ralph','1872-10-12','1958-08-26');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (111,'21st Century','German-Iranian','Djawadi','Ramin','1974-07-19',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (112,'Post-Romantic','German ','Strauss','Richard','1864-06-11','1949-09-08');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (113,'Romantic','German ','Wagner','Richard','1813-05-22','1883-02-13');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (114,'Romantic','German ','Schumann','Robert','1810-06-08','1856-07-29');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (115,'20th Century','American ','Barber','Samuel','1910-03-09','1981-01-23');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (116,'Modern','American ','Joplin','Scott','1867-01-01','1917-04-01');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (117,'20th Century','Russian','Prokofiev','Sergei','1891-04-27','1953-03-05');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (118,'20th Century','American ','Sondheim','Stephen','1930-03-22',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (119,'Contemporary','American ','Jablonsky','Steve','1970-10-09',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (120,'20th Century','American ','Reich','Steve','1936-10-03',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (121,'20th Century','American ','Riley','Terry','1935-06-24',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (122,'Renaissance','English','Tallis','Thomas','1505-01-01','1585-12-03');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (123,'20th Century','American ','Handy','W. C.','1873-11-16','1958-03-28');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (124,'Baroque','English ','Byrd','William','1543-01-01','1623-07-04');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (125,'Contemporary','Belgian ','Mertens','Wim','1953-05-14',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (126,'Classical','Austrian','Mozart','Wolfgang Amadeus','1756-01-27','1791-12-05');
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (127,'Contemporary','Japanese ','Kanno','Yoko','1964-03-19',NULL);
INSERT INTO `Composers` (`composer_id`,`era`,`nationality`,`last_name`,`first_name`,`birth_date`,`death_date`) VALUES (128,'20th Century','Czech ','Janáček','Leoš','1854-07-03','1928-08-12');
