CREATE TABLE `Works` (
  `work_id` int NOT NULL AUTO_INCREMENT,
  `composer_id` int DEFAULT NULL,
  `work_type_id` int DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `key` varchar(20) DEFAULT NULL,
  `opus_no` varchar(50) DEFAULT NULL,
  `work_no` int DEFAULT NULL,
  `name` varchar(50) DEFAULT NULL,
  `completion_year` int DEFAULT NULL,
  PRIMARY KEY (`work_id`)
) 

INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (1,94,12,'String Quartet No. 1','F major','Op. 18',1,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (2,94,12,'String Quartet No. 2','G major','Op. 18',2,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (3,94,12,'String Quartet No. 3','D major','Op. 18',3,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (4,94,12,'String Quartet No. 4','C major','Op. 18',4,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (5,94,12,'String Quartet No. 5','A major','Op. 18',5,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (6,94,12,'String Quartet No. 6','B flat major','Op. 18',6,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (7,94,12,'String Quartet No. 7','F major','Op. 59',1,'Rasumovsky',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (8,94,12,'String Quartet No. 8','E major','Op. 59',2,'Rasumovsky',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (9,94,12,'String Quartet No. 9','C major','Op. 59',3,'Rasumovsky',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (10,94,12,'String Quartet No. 10','E flat major','Op. 74',NULL,'Harp',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (11,94,12,'String Quartet No. 11','F minor','Op. 95',NULL,'Serioso',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (12,94,12,'String Quartet No. 12','E flat major','Op. 127',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (13,94,12,'String Quartet No. 13','B flat major','Op. 130',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (14,94,12,'String Quartet No. 14','C sharp minor','Op. 131',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (15,94,12,'String Quartet No. 15','A minor','Op. 132',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (16,94,12,'Große Fuge','B flat major','Op. 133',NULL,'The Great Flight',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (17,94,12,'String Quartet No. 16','F major','Op. 135',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (18,94,7,'Septet','E flate major','Op. 20',NULL,'',1800);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (19,73,12,'String Quartet No. 1','C minor','Op. 51',1,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (20,73,12,'String Quartet No. 2','A minor','Op. 51',2,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (21,73,12,'String Quartet No. 3','B flat major','Op. 67',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (22,73,13,'String Quintet No. 1','F major','Op. 88',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (23,73,13,'String Quintet No. 2','G major','Op. 111',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (24,73,14,'String Sextet No. 1','B flat major','Op. 18',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (25,73,14,'String Sextet No. 2','G major','Op. 36',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (26,73,17,'Piano Quintet','F minor','Op. 34',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (27,73,21,'Clarinet Quintet','B minor','Op. 115',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (28,73,19,'Clarinet Trio','A minor','Op. 114',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (29,73,16,'Piano Quartet No. 1','G minor','Op. 25',NULL,'',1859);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (30,73,16,'Piano Quartet No. 2','A major','Op. 26',NULL,'',1862);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (31,73,16,'Piano Quartet No. 3','C minor','Op. 60',NULL,'',1875);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (32,126,32,'Flute Quartet No. 1','D major','K. 285',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (33,126,32,'Flute Quartet No. 2','G major','K. 285a',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (34,126,32,'Flute Quartet No. 3','C major','K. 171',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (35,126,32,'Flute Quartet No. 4','A major','K. 298',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (36,126,21,'Clarinet Quintet','A major','K. 581',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (37,126,31,'Horn Quintet','E flat major','K. 407',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (38,126,33,'Oboe Quartet','F major','K. 370',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (39,126,16,'Piano Quartet No. 1','G minor','K. 478',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (40,126,16,'Piano Quartet No. 2','E flat major','K. 493',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (41,126,34,'String Duo No. 1','G major','K. 423',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (42,126,34,'String Duo No. 2','B flat major','K. 424',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (43,126,10,'Divertimento','B flat major','K. 186 / 159b',NULL,'',1773);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (44,126,10,'Divertimento','E flat major','K. 166 / 159d',NULL,'',1773);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (45,19,7,'Septet','E flat major','Op. 65',NULL,'',1880);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (46,41,15,'Piano Trio','G minor','Op. 8',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (47,109,15,'Piano Trio','A minor','Op. 50',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (48,7,24,'Violin Sonata','F major','Op. 57 / B. 106',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (49,7,24,'Violin Sonatina','G major','Op. 100 / B. 183',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (50,7,14,'String Sextet','A major','Op. 48 / B. 80',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (51,7,13,'String Quintet No. 1','A minor','Op. 1 / B. 7',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (52,7,13,'String Quintet No. 2','G major','Op. 77 / B. 49',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (53,7,13,'String Quintet No. 3','E flat major','Op. 97 / B. 180',NULL,'',NULL);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (54,7,15,'Piano Trio No. 1','B flat major','B. 51',NULL,'',1875);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (55,7,15,'Piano Trio No. 2','G minor','B. 56',NULL,'',1876);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (56,7,15,'Piano Trio No. 3','F minor','B. 130',NULL,'',1883);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (57,7,15,'Piano Trio No. 4','E minor','B. 166',NULL,'Dumky',1891);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (58,7,17,'Piano Quintet No. 1','A major','Op. 5 / B. 28',NULL,'',1872);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (59,7,17,'Piano Quintet No. 2','A major','Op. 81 / B. 155',NULL,'',1887);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (60,7,16,'Piano Quartet No. 1','D major','Op. 23 / B. 53',NULL,'',1875);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (61,7,16,'Piano Quartet No. 2','E flat major','Op. 87 / B. 162',NULL,'',1889);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (62,7,4,'Bagatelles',NULL,'Op. 47',NULL,'',1878);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (63,7,12,'String Quartet No. 1','A major','B. 8',NULL,'',1862);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (64,7,12,'String Quartet No. 2','B flat major','B. 17',NULL,'',1869);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (65,7,12,'String Quartet No. 3','D major','B. 18',NULL,'',1869);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (66,7,12,'String Quartet No. 4','E minor','B. 19',NULL,'',1870);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (67,7,12,'String Quartet No. 5','F minor','B. 37',NULL,'',1873);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (68,7,12,'String Quartet No. 6','A minor','B. 40',NULL,'',1873);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (69,7,12,'String Quartet No. 7','A minor','B. 45',NULL,'',1874);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (70,7,12,'String Quartet No. 8','E major','B. 57',NULL,'',1876);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (71,7,12,'String Quartet No. 9','D minor','B. 75',NULL,'',1877);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (72,7,12,'String Quartet No. 10','E flat major','B. 92',NULL,'Slavonic',1879);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (73,7,12,'String Quartet No. 11','C major','B. 121',NULL,'',1881);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (74,7,12,'String Quartet No. 12','F major','B. 179',NULL,'American',1893);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (75,7,12,'String Quartet No. 13','G major','B. 192',NULL,'',1895);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (76,7,12,'String Quartet No. 14','A flat major','B. 193',NULL,'',1895);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (77,7,12,'Cypresses Quartet',NULL,'B. 152',NULL,'',1887);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (78,7,12,'Quartet Movement','F major','B. 120',NULL,'',1881);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (79,7,12,'Andante Appassionato','F major','B. 40a',NULL,'',1873);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (80,7,1,'Ballade','D minor','Op. 15 / B. 139',NULL,'',1884);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (81,40,12,'Minuet for String Quartet','D major','D. 86',NULL,'',1813);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (82,40,12,'String Quartet No. 1','G minor/B flat major','D. 18',NULL,'',1811);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (83,40,12,'String Quartet No. 2','C major','D. 32',NULL,'',1812);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (84,40,12,'String Quartet No. 3','B flat major','D. 36',NULL,'',1813);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (85,40,12,'String Quartet No. 4','C major','D. 46',NULL,'',1813);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (86,40,12,'String Quartet No. 5','B flat major','D. 68',NULL,'',1813);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (87,40,12,'String Quartet No. 6','D major','D. 74',NULL,'',1813);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (88,40,12,'String Quartet No. 7','D major','D. 94',NULL,'',1812);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (89,40,12,'String Quartet No. 8','B flat major','D. 112',NULL,'',1814);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (90,40,12,'String Quartet No. 9','G minor','D. 173',NULL,'',1815);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (91,40,12,'String Quartet No. 10','E flat major','D. 87',NULL,'',1813);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (92,40,12,'String Quartet No. 11','E major','D. 353',NULL,'',1816);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (93,40,12,'String Quartet No. 12','C minor','D. 703',NULL,'Quartettsatz',1820);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (94,40,12,'String Quartet No. 13','A minor','D. 804',NULL,'Rosamunde',1824);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (95,40,12,'String Quartet No. 14','D minor','D. 810',NULL,'Death and the Maiden',1824);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (96,40,12,'String Quartet No. 15','G major','D. 887',NULL,'',1826);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (97,40,12,'Five Minuets with Six Trios',NULL,'D. 89',NULL,'',1813);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (98,97,24,'Violin Sonata No. 1','A minor','M. 12',NULL,'',1897);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (99,97,24,'Violin Sonata No. 2','G major','M. 77',NULL,'',1927);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (100,97,1,'Sonata for Violin and Cello','A minor','M. 73',NULL,'',1922);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (101,97,15,'Piano Trio','A minor','M. 67',NULL,'',1914);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (102,97,12,'String Quartet','F major','M. 35',NULL,'',1903);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (103,97,7,'Introduction and Allegro','G flat major','M. 46',NULL,'',1905);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (104,114,24,'Violin Sonata No. 1','A minor','Op. 105',NULL,'',1851);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (105,114,24,'Violin Sonata No. 2','D minor','Op. 121',NULL,'',1851);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (106,114,1,'Adagio and Allegro','A flat major','Op. 70',NULL,'',1849);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (107,114,1,'Three Romances for Oboe and Piano',NULL,'Op. 94',NULL,'',1849);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (108,114,16,'Piano Quartet','E flat major','Op. 47',NULL,'',1842);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (109,114,17,'Piano Quintet','E flat major','Op. 44',NULL,'',1842);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (110,114,1,'Märchenbilder',NULL,'Op. 113',NULL,'',1851);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (111,114,1,'Fantasiestücke',NULL,'Op. 73',NULL,'',1849);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (112,114,1,'F-A-E Sonata',NULL,NULL,NULL,'',1853);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (113,75,12,'String Quartet in Four Parts',NULL,NULL,NULL,'',1950);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (114,83,12,'Quartet in B flat major','B Flat major','Op. 1',5,'',1764);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (115,83,12,'The Seven Last Words of our Saviour on the Cross',NULL,'Op. 51',NULL,'',1787);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (116,83,12,'String Quartet No. 1','B flat major','Op. 1',1,'La Chasse',1764);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (117,83,12,'String Quartet No. 2','E flat major','Op. 1',2,'',1764);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (118,83,12,'String Quartet No. 3','D major','Op. 1',3,'',1764);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (119,83,12,'String Quartet No. 4','G major','Op. 1',4,'',1764);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (120,83,12,'String Quartet No. 5','E flat major','Op. 1',0,'',1764);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (121,83,12,'String Quartet No. 6','C major','Op. 1',6,'',1764);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (122,83,12,'String Quartet No. 7','A major','Op. 2',1,'',1765);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (123,83,12,'String Quartet No. 8','E major','Op. 2',2,'',1765);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (124,83,12,'Quartet in E flat major','E flat major','Op. 2',3,'',1765);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (125,83,12,'String Quartet No. 9','F major','Op. 2',4,'',1765);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (126,83,12,'Quartet in D major','D major','Op. 2',5,'',1765);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (127,83,12,'String Quartet No. 10','B flat major','Op. 2',6,'',1765);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (128,83,12,'String Quartet No. 11','D minor','Op. 9',4,'',1769);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (129,83,12,'String Quartet No. 12','C major','Op. 9',1,'',1769);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (130,83,12,'String Quartet No. 13','G major','Op. 9',3,'',1769);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (131,83,12,'String Quartet No. 14','E flat  major','Op. 9',2,'',1769);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (132,83,12,'String Quartet No. 15','B flat  major','Op. 9',5,'',1769);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (133,83,12,'String Quartet No. 16','A major','Op. 9',6,'',1769);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (134,83,12,'String Quartet No. 17','F major','Op. 17',2,'',1771);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (135,83,12,'String Quartet No. 18','E major','Op. 17',1,'',1771);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (136,83,12,'String Quartet No. 19','C minor','Op. 17',4,'',1771);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (137,83,12,'String Quartet No. 20','D major','Op. 17',6,'',1771);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (138,83,12,'String Quartet No. 21','E flat  major','Op. 17',3,'',1771);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (139,83,12,'String Quartet No. 22','G major','Op. 17',5,'',1771);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (140,83,12,'String Quartet No. 23','F minor','Op. 20',5,'',1772);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (141,83,12,'String Quartet No. 24','A major','Op. 20',6,'',1772);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (142,83,12,'String Quartet No. 25','C major','Op. 20',2,'',1772);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (143,83,12,'String Quartet No. 26','G minor','Op. 20',3,'',1772);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (144,83,12,'String Quartet No. 27','D major','Op. 20',4,'',1772);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (145,83,12,'String Quartet No. 28','E flat major','Op. 20',1,'',1772);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (146,83,12,'String Quartet No. 29','G major','Op. 33',5,'How Do You Do?',1781);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (147,83,12,'String Quartet No. 30','E flat major','Op. 33',2,'The Joke',1781);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (148,83,12,'String Quartet No. 31','B minor','Op. 33',1,'',1781);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (149,83,12,'String Quartet No. 32','C major','Op. 33',3,'The Bird',1781);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (150,83,12,'String Quartet No. 33','D major','Op. 33',6,'',1781);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (151,83,12,'String Quartet No. 34','B flat major','Op. 33',4,'',1781);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (152,83,12,'String Quartet No. 35','D minor','Op. 42',NULL,'',1785);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (153,83,12,'String Quartet No. 36','B flat major','Op. 50',1,'',1787);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (154,83,12,'String Quartet No. 37','C major','Op. 50',2,'',1787);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (155,83,12,'String Quartet No. 38','E flat major','Op. 50',3,'',1787);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (156,83,12,'String Quartet No. 39','F sharp minor','Op. 50',4,'',1787);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (157,83,12,'String Quartet No. 40','F major','Op. 50',5,'Dream',1787);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (158,83,12,'String Quartet No. 41','D major','Op. 50',6,'The Frog',1787);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (159,83,12,'String Quartet No. 42','C major','Op. 54',2,'',1788);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (160,83,12,'String Quartet No. 43','G major','Op. 54',1,'',1788);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (161,83,12,'String Quartet No. 44','E major','Op. 54',3,'',1788);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (162,83,12,'String Quartet No. 45','A major','Op. 55',1,'',1788);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (163,83,12,'String Quartet No. 46','F minor','Op. 55',2,'Razor',1788);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (164,83,12,'String Quartet No. 47','B flat major','Op. 55',3,'',1788);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (165,83,12,'String Quartet No. 48','C major','Op. 64',1,'',1790);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (166,83,12,'String Quartet No. 49','B minor','Op. 64',2,'',1790);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (167,83,12,'String Quartet No. 50','B flat major','Op. 64',3,'',1790);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (168,83,12,'String Quartet No. 51','G major','Op. 64',4,'',1790);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (169,83,12,'String Quartet No. 52','E flat major','Op. 64',6,'',1790);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (170,83,12,'String Quartet No. 53','D major','Op. 64',5,'The Lark',1790);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (171,83,12,'String Quartet No. 54','B flat major','Op. 71',1,'',1793);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (172,83,12,'String Quartet No. 55','D major','Op. 71',2,'',1793);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (173,83,12,'String Quartet No. 56','E flat major','Op. 71',3,'',1793);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (174,83,12,'String Quartet No. 57','C major','Op. 74',1,'',1793);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (175,83,12,'String Quartet No. 58','F major','Op. 74',2,'',1793);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (176,83,12,'String Quartet No. 59','G minor','Op. 74',3,'Rider',1793);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (177,83,12,'String Quartet No. 60','G major','Op. 76',1,'',1797);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (178,83,12,'String Quartet No. 61','D minor','Op. 76',2,'Fifths',1797);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (179,83,12,'String Quartet No. 62','C major','Op. 76',3,'Emperor',1797);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (180,83,12,'String Quartet No. 63','B flat major','Op. 76',4,'Sunrise',1797);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (181,83,12,'String Quartet No. 64','D major','Op. 76',5,'Friedhofsquartett',1797);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (182,83,12,'String Quartet No. 65','E flat major','Op. 76',6,'',1797);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (183,83,12,'String Quartet No. 66','G major','Op. 77',1,'',1799);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (184,83,12,'String Quartet No. 67','F major','Op. 77',2,'',1799);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (185,83,12,'String Quartet No. 68','D minor','Op. 103',NULL,'',1803);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (186,128,12,'String Quartet No. 1',NULL,NULL,NULL,'Kreutzer Sonata',1923);
INSERT INTO `Works` (`work_id`,`composer_id`,`work_type_id`,`title`,`key`,`opus_no`,`work_no`,`name`,`completion_year`) VALUES (187,128,12,'String Quartet No. 2',NULL,NULL,NULL,'Intimate Letters',1928);
